version: "3.9"
services:
  backend:
    build: ./backend
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    depends_on:
      - "redis"
  redis:
    image: redis
    command: redis-server --requirepass "$REDIS_PASSWORD"
    ports:
      - "6379:6379"
