version: "3.9"
services:
  backend:
    build: ./backend
    # command: ["sh", "-c", "pip install debugpy -t /tmp && pipenv run python 
    # /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
    #  --nothreading --noreload"]
    command: ["sh", "-c", "pipenv install debugpy && pipenv run python manage.py runserver 0.0.0.0:8000"]
    environment:
      - ENV=DEBUG
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - "redis"
  redis:
    image: redis
    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - "6379:6379"
