# Generated by Django 3.2.8 on 2021-10-18 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_finished', models.DateTimeField(auto_now_add=True)),
                ('loser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser', to=settings.AUTH_USER_MODEL)),
                ('winner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
