# Generated by Django 4.0a1 on 2021-10-21 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_change_history_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='date_finished',
            new_name='finished',
        ),
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
