# Generated by Django 4.0a1 on 2021-10-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_rename_date_finished_game_finished_game_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='moves',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
