# Generated by Django 4.0a1 on 2021-11-01 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0005_alter_game_loser_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='played_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
